version: "3.2"

services:

  vernemq:
    build: vernemq

  dev:
    image: ruby:2.5
    depends_on:
      - vernemq
    volumes:
      - .:/work
      - gem-cache:/usr/local/bundle
    working_dir: /work
    command: /bin/bash

volumes:
  gem-cache: ~
