version: "3.2"

volumes:
  vmq_data: {}

services:

  vernemq:
    image: erlio/docker-vernemq:1.3.0
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: "debug"
      DOCKER_VERNEMQ_LEVELDB__MAXIMUM_MEMORY__PERCENT: "20"
    hostname: vernemq
    volumes:
      - .:/work

  dev:
    build: dev
    hostname: dev
    depends_on:
      - vernemq
    volumes:
      - .:/work
      - gem-cache:/usr/local/bundle
    working_dir: /work
    command: /bin/bash
    environment:
      MQTT_HOST: vernemq
      PATH: /usr/local/bundle/bin:/usr/local/bin:/usr/bin:/bin:/work/bin

volumes:
  gem-cache: ~
