version: "3.2"

services:

  vernemq:
    build: vernemq
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
    hostname: vernemq

  dev:
    build: dev
    hostname: dev
    depends_on:
      - vernemq
    volumes:
      - .:/work
      - gem-cache:/usr/local/bundle
    working_dir: /work
    command: /bin/bash
    environment:
      MQTT_HOST: vernemq

volumes:
  gem-cache: ~
